# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: CI

env:
  DOCKER_BUILDKIT: 1

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1

      - name: Install dependencies
        run: |
          docker run --rm -v `pwd`:/app composer install --ignore-platform-reqs

      - name: Run tests in the just build app image
        run: |
          docker-compose run --rm test sh -c "cd /var/www/html && ./vendor/bin/phpunit --coverage-clover coverage.xml --testdox -c phpunit-ci.xml"

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
